spring.datasource.url=jdbc:postgresql://localhost:5432/tu_db
spring.datasource.username=tu_user
spring.datasource.password=tu_password



#MailTrap- desarrollo
#spring.mail.host=sandbox.smtp.mailtrap.io
#spring.mail.port=2525
#spring.mail.username=tu_username
#spring.mail.password=tu_password
#app.mail.from=example@mailtrap.io

# Gmail - producción
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_username
spring.mail.password=tu_password
