package com.devops.backend.shared.email;

public enum EmailJobType {
    REEMBOLSO_SOLICITUD_USUARIO,
    REEMBOLSO_SOLICITUD_ORGANIZADOR,
    REEMBOLSO_APROBADA,
    REEMBOLSO_RECHAZADA,
    REEMBOLSO_REEMBOLSADA
}
